events {}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html index.htm;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            # This proxy_pass is not used in our current setup but is the
            # typical way to proxy backend requests from Nginx if needed.
            # In our case, the Angular app's HttpClient handles this directly.
            # It's a good practice to show this.
            # proxy_pass http://backend:8080/;
        }
    }
}
